
import Metodos.ListaA;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Heber
 */
public class ListaAlumnos extends javax.swing.JFrame {

    /**
     * Creates new form ListaAlumnos
     */
    public ListaAlumnos() {
        initComponents();
        setLocationRelativeTo(null);
        btnBuscar.doClick(1);
    }

    FrameAlumnos fAlumnos = new FrameAlumnos();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistros = new javax.swing.JTable();
        btnBuscar = new javax.swing.JToggleButton();
        cboxFiltro = new javax.swing.JComboBox<>();
        txtFiltro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnEliminarRegistro = new javax.swing.JToggleButton();
        btnNuevoRegistro = new javax.swing.JButton();
        btnRefrescarLista = new javax.swing.JToggleButton();

        setTitle("Lista de Alumnos");

        tblRegistros = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblRegistros.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tblRegistros.setColumnSelectionAllowed(false);
        tblRegistros.getTableHeader().setReorderingAllowed(false);
        tblRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegistrosMouseClicked(evt);
            }
        });
        tblRegistros.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblRegistrosPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegistros);

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-find-user-male-50.png"))); // NOI18N
        btnBuscar.setText("Buscar:");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        cboxFiltro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Nombre", "Apellido Paterno", "Apellido Materno", "Materia", "Fecha", " " }));
        cboxFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxFiltroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Filtro:");

        btnEliminarRegistro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-trash-50.png"))); // NOI18N
        btnEliminarRegistro.setText("Eliminar");
        btnEliminarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarRegistroActionPerformed(evt);
            }
        });

        btnNuevoRegistro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-new-50.png"))); // NOI18N
        btnNuevoRegistro.setText("Nuevo");
        btnNuevoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoRegistroActionPerformed(evt);
            }
        });

        btnRefrescarLista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRefrescarLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-synchronize-50.png"))); // NOI18N
        btnRefrescarLista.setText("Refrescar");
        btnRefrescarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 850, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFiltro, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevoRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefrescarLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarRegistro)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboxFiltro)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnRefrescarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNuevoRegistro)
                        .addComponent(btnEliminarRegistro)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ListaA lista = new ListaA();
        lista.Buscar(txtFiltro.getText(), cboxFiltro.getSelectedItem().toString(), tblRegistros);


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cboxFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxFiltroActionPerformed
    }//GEN-LAST:event_cboxFiltroActionPerformed

    private void btnEliminarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarRegistroActionPerformed
        int dialog = JOptionPane.showConfirmDialog(null, "¿Seguro que desea eliminar el registro?", "Eliminar registro", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (dialog == JOptionPane.YES_OPTION) {
            try {
                int row = tblRegistros.getSelectedRow();
                DefaultTableModel model = (DefaultTableModel) tblRegistros.getModel();
                String selected = model.getValueAt(row, 0).toString();

                if (row >= 0) {

                    model.removeRow(row);

                    try {
                        Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb", "root", "root");
                        PreparedStatement ps = conn.prepareStatement("DELETE FROM alumnos WHERE idalumnos='" + selected + "' ");
                        ps.executeUpdate();
                    } catch (SQLException w) {
                        JOptionPane.showMessageDialog(null, "Error de conexion");
                    }
                }
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Selecciona algún registro para eliminar");
            }
        }


    }//GEN-LAST:event_btnEliminarRegistroActionPerformed

    private void btnNuevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoRegistroActionPerformed

        FrameAlumnos nuevo = new FrameAlumnos();
        nuevo.setVisible(true);

    }//GEN-LAST:event_btnNuevoRegistroActionPerformed

    private void tblRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegistrosMouseClicked

        if (evt.getClickCount() == 2) {
            try {

                int index = tblRegistros.getSelectedRow();
                TableModel model = tblRegistros.getModel();

                //Declaración de las variables según la tabla
                String ID = model.getValueAt(index, 0).toString();
                String Nombres = model.getValueAt(index, 1).toString();
                String ApellidoP = model.getValueAt(index, 2).toString();
                String ApellidoM = model.getValueAt(index, 3).toString();
                String NombreTut = model.getValueAt(index, 4).toString();
                String ApellidoPTut = model.getValueAt(index, 5).toString();
                String ApellidoMTut = model.getValueAt(index, 6).toString();
                String Nombretut2 = model.getValueAt(index, 7).toString();
                String ApellidoPTut2 = model.getValueAt(index, 8).toString();
                String ApellidoMTut2 = model.getValueAt(index, 9).toString();
                String Direccion = model.getValueAt(index, 10).toString();
                String Colonia = model.getValueAt(index, 11).toString();
                String Telefono = model.getValueAt(index, 12).toString();
                String Celular = model.getValueAt(index, 13).toString();
                String Correo = model.getValueAt(index, 14).toString();
                String Escuela = model.getValueAt(index, 15).toString();
                String Grado = model.getValueAt(index, 16).toString();
                String Turno = model.getValueAt(index, 17).toString();
                String Materia = model.getValueAt(index, 18).toString();
                String Comentarios = model.getValueAt(index, 19).toString();
                String Fecha = model.getValueAt(index, 20).toString();

                fAlumnos.setVisible(true);
                fAlumnos.pack();

                //Acomodo de las variables en la frame de registro de alumnos
                fAlumnos.txtID.setText(ID);
                fAlumnos.txtNalumno.setText(Nombres);
                fAlumnos.txtAPalumno.setText(ApellidoP);
                fAlumnos.txtAMalumno.setText(ApellidoM);
                fAlumnos.txtNtutor.setText(NombreTut);
                fAlumnos.txtAPtut.setText(ApellidoPTut);
                fAlumnos.txtAMtut.setText(ApellidoMTut);
                fAlumnos.txtNtutor2.setText(Nombretut2);
                fAlumnos.txtAPtut2.setText(ApellidoPTut2);
                fAlumnos.txtAMtut2.setText(ApellidoMTut2);
                fAlumnos.txtDireccion.setText(Direccion);
                fAlumnos.txtColonia.setText(Colonia);
                fAlumnos.txtTelefono.setText(Telefono);
                fAlumnos.txtCelular.setText(Celular);
                fAlumnos.txtCorreo.setText(Correo);
                fAlumnos.txtEscuela.setText(Escuela);
                fAlumnos.cboxGrado.setSelectedItem(Grado);
                fAlumnos.cboxTurno.setSelectedItem(Turno);
                fAlumnos.cboxMateria.setSelectedItem(Materia);
                fAlumnos.txtComentarios.setText(Comentarios);
                fAlumnos.Calendario.setDateFormatString(Fecha);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_tblRegistrosMouseClicked

    private void tblRegistrosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblRegistrosPropertyChange

    }//GEN-LAST:event_tblRegistrosPropertyChange

    private void btnRefrescarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarListaActionPerformed
        ListaA lista = new ListaA();
        lista.Buscar(txtFiltro.getText(), cboxFiltro.getSelectedItem().toString(), tblRegistros);

    }//GEN-LAST:event_btnRefrescarListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBuscar;
    private javax.swing.JToggleButton btnEliminarRegistro;
    private javax.swing.JButton btnNuevoRegistro;
    private javax.swing.JToggleButton btnRefrescarLista;
    private javax.swing.JComboBox<String> cboxFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblRegistros;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
